/* autogenerated by Processing revision 1286 on 2023-03-08 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import peasy.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Main extends PApplet {

Button startButton;
Button CH4;
Button H2O;
Button NH3;
Button C3H6O;
Button clear;

ArrayList<H2O> water = new ArrayList<H2O>();
ArrayList<CH4> methane = new ArrayList<CH4>();
ArrayList<NH3> ammonia = new ArrayList<NH3>();
ArrayList<C3H6O> acetone = new ArrayList<C3H6O>();



boolean play = false;
int i = 0;
int draggingIndex;
boolean draggingH2O, draggingCH4, draggingNH3, draggingC3H6O;
boolean clickingH2O, clickingCH4, clickingNH3, clickingC3H6O, clickingReset;



PeasyCam cam;

 public void setup() {
  /* size commented out by preprocessor */;
  textSize(50);
  textAlign(CENTER);
  rectMode(CENTER);
  startButton = new Button(width/2, height/2+400, 400, 200);
  CH4 = new Button(width-100, height-150, 200, 300);
  H2O = new Button(width-300, height-150, 200, 300);
  NH3 = new Button(width-500, height-150, 200, 300);
  C3H6O = new Button(width-700, height-150, 200, 300);
  clear = new Button(100, height-150, 200, 300);
  cam = new PeasyCam(this, width/2, height/2, 0, 1000);
}

 public void draw() {
  noStroke();
  boolean start = startButton.mouseClicked();
  boolean hoverH2O = H2O.hover(mouseX, mouseY);
  boolean hoverCH4 = CH4.hover(mouseX, mouseY);
  boolean hoverNH3 = NH3.hover(mouseX, mouseY);
  boolean hoverC3H6O = C3H6O.hover(mouseX, mouseY);
  boolean hoverReset = clear.hover(mouseX, mouseY);
  boolean clickedH2O = H2O.mouseClicked();
  boolean clickedCH4 = CH4.mouseClicked();
  boolean clickedNH3 = NH3.mouseClicked();
  boolean clickedC3H6O = C3H6O.mouseClicked();
  boolean reset = clear.mouseClicked();

  //Making all them true
  if(reset){
    clickingReset = true;
  }
  if (clickedH2O) {
    clickingH2O = true;
  }
  if (clickedCH4) {
    clickingCH4 = true;
  }
  if (clickedNH3) {
    clickingNH3 = true;
  }
  if (clickedC3H6O) {
    clickingC3H6O = true;
  }

  if (start) {
    play = true;
  }
  //if(){
    
  //}
  if (play) {
    background(0);
    fill(255);
    cam.beginHUD();
    CH4.display();
    H2O.display();
    NH3.display();
    C3H6O.display();
    clear.display();

    cam.endHUD();

    if (!mousePressed) {
      draggingH2O = false;
      clickingH2O = false;
      draggingCH4 = false;
      clickingCH4 = false;
      draggingNH3 = false;
      clickingNH3 = false;
      draggingC3H6O = false;
      clickingC3H6O = false;
      clickingReset = false;
    }

    //Display Molecules
    if (clickingH2O || clickingCH4 || clickingNH3 || clickingC3H6O) {
      cam.setActive(false);
    } else {
      cam.setActive(true);
    }
    println("MouseX: "+ mouseX);

    if (water.size() == 2) {
      H2O w1 = water.get(0);
      H2O w2 = water.get(1);
      w1.moveCenter(w2.x, w2.y, w1.x+125, w1.y+300);
      w2.x = w1.xl;
      w2.y = w1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("There is hydrogen bond between the Oxygen and the Hydrogen. This is due to the fact that Oxygen is extremely electronegative, making the molecule very polar", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (methane.size() == 2) {
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("These are 2 non-polar molecules", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (ammonia.size() == 2) {
      NH3 a1 = ammonia.get(0);
      NH3 a2 = ammonia.get(1);
      a1.moveCenter(a2.x, a2.y, a1.x-150, a1.y+200);
      a2.x = a1.xl;
      a2.y = a1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("There is hydrogen bond between the Nitrogen and the Hydrogen. This is due to the fact that Nitrogen is extremely electronegative, making the molecule very polar", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (acetone.size() == 2) {
      C3H6O c1 = acetone.get(0);
      C3H6O c2 = acetone.get(1);
      c1.moveCenter(c2.x, c2.y, c1.x-380, c1.y+380);
      c2.x = c1.xl;
      c2.y = c1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("There is dipole dipole bond between the Oxygen and the Hydrogen. This is due to the fact that Oxygen is extremely electronegative, making the molecule very polar, but there is not hydrogen attatched to the Oxygen so it is not a hydrogen bond", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (water.size() == 1 && methane.size() == 1) {
      H2O w1 = water.get(0);
      CH4 m1 = methane.get(0);
      w1.moveCenter(m1.x, m1.y, w1.x, w1.y-300);
      m1.x = w1.xl;
      m1.y = w1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a dipole induced dipole, as methane which is usually non-polar becomes a dipole when it is close to H2O", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (water.size() == 1 && ammonia.size() == 1) {
      H2O w1 = water.get(0);
      NH3 a1 = ammonia.get(0);
      w1.moveCenter(a1.x, a1.y, w1.x+150, w1.y-200);
      a1.x = w1.xl;
      a1.y = w1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a hydrogen bond between the oxygen and the hydrogen as the oxygen has hydrogen attached to it making it highly polar", width-150, 0+150, 300, 300);
      cam.endHUD();
    }

    if (water.size() == 1 && acetone.size() == 1) {
      H2O w1 = water.get(0);
      C3H6O c1 = acetone.get(0);
      w1.moveCenter(c1.x, c1.y, w1.x+125, w1.y+500);
      c1.x = w1.xl;
      c1.y = w1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a dipole dipole as it is between 2 polar molecules", width-150, 0+150, 300, 300);
      cam.endHUD();
    }
    
    if (ammonia.size() == 1 && methane.size() == 1) {
      NH3 a1 = ammonia.get(0);
      CH4 m1 = methane.get(0);
      a1.moveCenter(m1.x, m1.y, a1.x, a1.y-300);
      m1.x = a1.xl;
      m1.y = a1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a dipole induced dipole as methane becomes a polar molecule due to the ammonia", width-150, 0+150, 300, 300);
      cam.endHUD();
    }
    
    if (ammonia.size() == 1 && acetone.size() == 1) {
      NH3 a1 = ammonia.get(0);
      C3H6O c1 = acetone.get(0);
      a1.moveCenter(c1.x, c1.y, a1.x-150, a1.y+400);
      c1.x = a1.xl;
      c1.y = a1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a dipole dipole interaction as it is between two polar molecules", width-150, 0+150, 300, 300);
      cam.endHUD();
    }
    
    if (methane.size() == 1 && acetone.size() == 1) {
      CH4 m1 = methane.get(0);
      C3H6O c1 = acetone.get(0);
      m1.moveCenter(c1.x, c1.y, m1.x, m1.y+500);
      c1.x = m1.xl;
      c1.y = m1.yl;
      cam.beginHUD();
      fill(255);
      textSize(20);
      text("This is a dipole induced molecule as methane which is non-polar, becomes a dipole due to the acetone", width-150, 0+150, 300, 300);
      cam.endHUD();
    }
    
    for (H2O waterpart : water) {
      waterpart.display();
    }

    for (CH4 methanepart : methane) {
      methanepart.display();
    }

    for (NH3 ammoniapart : ammonia) {
      ammoniapart.display();
    }

    for (C3H6O acetonepart : acetone) {
      acetonepart.display();
    }

    //Info for all of the buttons
    cam.beginHUD();
    textAlign(CENTER);
    fill(0);
    if(hoverReset){
      textSize(30);
      String clean = "Clicking this will clear everything off the screen";
      text(clean, 100, height-150, 200, 300);
    }else{
      textSize(60);
      text("Reset", 100, height-150);
    }
    if (hoverCH4) {
      textSize(30);
      String CH4 = "This is a chemical that is most commonly known as methane.";
      text(CH4, width-100, height-150, 200, 300);
    } else {
      textSize(60);
      text("CH4", width-100, height-150);
    }
    if (hoverH2O) {
      textSize(30);
      String H2O = "This is a chemical that is most commonly known as water.";
      text(H2O, width-300, height-150, 200, 300);
    } else {
      textSize(60);
      text("H2O", width-300, height-150);
    }
    if (hoverNH3) {
      textSize(30);
      String NH3 = "This is a chemical that is most commonly known as ammonia.";
      text(NH3, width-500, height-150, 200, 300);
    } else {
      textSize(60);
      text("NH3", width-500, height-150);
    }
    if (hoverC3H6O) {
      textSize(30);
      String C3H6O = "This is a chemical that is most commonly known as acetone.";
      text(C3H6O, width-700, height-150, 200, 300);
    } else {
      textSize(60);
      text("C3H6O", width-700, height-150);
    }
    cam.endHUD();

  } else {
    cam.beginHUD();
    background(0);
    fill(255);
    boolean hover = startButton.hover(mouseX, mouseY);
    if (hover) {
      fill(100);
    } else {
      fill(255);
    }
    startButton.display();
    fill(255);
    textAlign(CENTER);
    rectMode(CENTER);
    textSize(60);
    text("Welcome to the intermolecular forces model", width/2, height/2-230);
    text("By Evan Luo", width/2, height/2-180);
    textSize(20);
    text("How to play: Hover over any molecule for a description of it and then you can click and drag to position it onto the screen. If you drag and drop another molecule to the screen, you can see how it interacts with the other molecule as well a description the intermolecular force. There is a maximum limit of 2 molecules on the screen. Use right click and drag to roate your camera around the molecule. Use the scroll wheel to zoom in and out. If you would like to reset your camera back to it's starting position, double click, it needs to be in its starting position if you want to create more molecules", width/2, height/2+100,1500,300);
    fill(0);
    text("Click to Start", width/2, height/2+400);
    cam.endHUD();
  }
}


 public void mousePressed() {
  cam.reset();
  for (int i = water.size() - 1; i >= 0; i--) {
    if (H2O.hover(mouseX, mouseY)) {
      draggingH2O = true;
      draggingIndex = i;
      break;
    }
  }
  for (int i = methane.size() - 1; i >= 0; i--) {
    if (CH4.hover(mouseX, mouseY)) {
      draggingCH4 = true;
      draggingIndex = i;
      break;
    }
  }

  for (int i = ammonia.size() - 1; i >= 0; i--) {
    if (NH3.hover(mouseX, mouseY)) {
      draggingNH3 = true;
      draggingIndex = i;
      break;
    }
  }
  for (int i = acetone.size() - 1; i >= 0; i--) {
    if (C3H6O.hover(mouseX, mouseY)) {
      draggingC3H6O = true;
      draggingIndex = i;
      break;
    }
  }
}

 public void mouseDragged() {
  if (draggingH2O && water.size() == 0) {
    H2O w = water.get(draggingIndex);
    w.x = mouseX;
    w.y = mouseY;
  }

  if (draggingCH4 && methane.size() == 0) {
    CH4 m = methane.get(draggingIndex);
    m.x = mouseX;
    m.y = mouseY;
  }
  if (draggingNH3 && ammonia.size() == 0) {
    NH3 m = ammonia.get(draggingIndex);
    m.x = mouseX;
    m.y = mouseY;
  }
  if (draggingC3H6O && acetone.size() == 0) {
    C3H6O m = acetone.get(draggingIndex);
    m.x = mouseX;
    m.y = mouseY;
  }
}

 public void mouseReleased() {
  if (water.size() + methane.size() + ammonia.size() + acetone.size() < 2) {
    if (clickingH2O) {
      water.add(new H2O(mouseX, mouseY));
    }
    if (clickingCH4) {
      methane.add(new CH4(mouseX, mouseY, 0));
    }
    if (clickingNH3) {
      ammonia.add(new NH3(mouseX, mouseY, 0));
    }

    if (clickingC3H6O) {
      acetone.add(new C3H6O(mouseX, mouseY, 0));
    }
  }
  if(clickingReset){
    water.clear();
    methane.clear();
    ammonia.clear();
    acetone.clear();
  }
}
// polar bonds have a difference of 0.4 to 1.7
// lower than 0.4 is more covalent
// higher is more ionic

class Atom {
  PShape atom;
  PImage image;
  float size;
  float weight;
  float x;
  float y;
  float z;
  
  Atom(float size, float weight, String img){
    this.size = size;
    this.weight = weight;
    this.image = loadImage(img);
  }
  

 public void display(float x, float y, float z){
    fill(255);
    lights();
    sphereDetail(10);
    noStroke();
    pushMatrix();
    translate(x, y, z);
    rotateY(PI/2);
    atom = createShape(SPHERE,size);
    atom.setTexture(image);
    shapeMode(CENTER);
    shape(atom,0,0);
    popMatrix();
    fill(0);
    
}

}
class Button {
  float x, y, w, h;
  int colr;

  Button(float x, float y, float w, float h) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;

  }

   public void display() {
    shapeMode(CENTER);
    rect(x, y, w, h);
  }

  //Determine if mouse is being pressed
   public boolean hover(float mx, float my){
      if (mx >= x-(w/2) && mx <= x + (w/2) && my >= y-(h/2) && my <= y + (h/2)) {
        return true;
      } else {
        return false;
      }
  }
   
  
   public boolean mouseClicked() {
    if (mousePressed) {
      if (mouseX >= x-(w/2) && mouseX <= x + (w/2) && mouseY >= y-(h/2) && mouseY <= y + (h/2)) {
        return true;
      } else {
        return false;
      }
    } else {
      return false;
    }
  }
}

class C3H6O extends Molecule {

  float x, y, z;

  C3H6O(float x_, float y_, float z_) {
    super();
    x = x_;
    y = y_;
    z = z_;
    carbon = new Atom(85.0f, 2.55f, "Carbon.jpg");
    carbon = new Atom(85.0f, 2.55f, "Carbon.jpg");
    carbon = new Atom(85.0f, 2.55f, "Carbon.jpg");
    carbon = new Atom(85.0f, 2.55f, "Carbon.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    oxygen = new Atom(76, 3.44f, "Oxygen.jpg");
  }


   public void display() {
    hydrogen1.display(x+325, y, 0);
    hydrogen1.display(x-325, y, 0);
    hydrogen1.display(x+170, y+150, +200);
    hydrogen1.display(x+170, y+150, -150);
    hydrogen1.display(x-170, y+150, +200);
    hydrogen1.display(x-170, y+150, -150);
    carbon.display(x+170.0f, y+85, 0);
    carbon.display(x-170.0f, y+85, 0);
    carbon.display(x, y, 0);
    oxygen.display(x,y-200.0f,0);
  }
}
Atom carbon;

class CH4 extends Molecule {
  
  float x, y, z;
  
  CH4(float x_, float y_, float z_) {
    super();
    x = x_;
    y = y_;
    z = z_;
    carbon = new Atom(85.0f, 2.55f, "Carbon.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
  }


   public void display() {
    hydrogen1.display(x, y+125.0f, 0);
    hydrogen1.display(x-120.0f, y-125.0f, z-95.0f);
    hydrogen1.display(x+120.0f, y-125.0f, z-95.0f);
    hydrogen1.display(x, y-125.0f, z+160.0f);
    carbon.display(x, y-50.0f, -15.0f);
  }

}
Atom hydrogen1;
Atom oxygen;




class H2O extends Molecule {

  float x, y;

  H2O(float x_, float y_) {
    super();
    print("MouseX: " + mouseX);
    x = x_;
    y = y_;
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f, "Hydrogen.jpg");
    oxygen = new Atom(76, 3.44f, "Oxygen.jpg");
  }


   public void display() {
    hydrogen1.display(x-125.0f, y+125.0f, 0);
    hydrogen1.display(x+125.0f, y+125.0f, 0);
    oxygen.display(x, y, 0);
    
  }

}

PVector location, target;

class Molecule {
  float xl, yl, speedX, speedY, rotation;
  float speed = 5;
  
  Molecule(){
  }
  
   public void moveCenter(float startX, float startY, float targetX, float targetY){
    xl = startX;
    yl = startY;
    location = new PVector(xl, yl);
    target = new PVector(targetX, targetY);
    rotation = atan2(location.y - target.y, location.x - target.x) / PI * 180 + random(-2, 2);
    //rotation = PVector.angleBetween(target, location);
    speedX = cos(rotation/180*PI)*speed;
    speedY = sin(rotation/180*PI)*speed;
    if(PVector.dist(location, target) >= 10){
      xl = location.x - speedX;
      yl = location.y - speedY;
    }
    println("Target: "+target);
    println("Location: "+location);
    println("Rotation: "+rotation);
  }
  
  
}
Atom nitrogen;

class NH3 extends Molecule {
  
  float x, y, z;
  
  NH3(float x_, float y_, float z_) {
    super();
    x = x_;
    y = y_;
    z = z_;
    nitrogen = new Atom(77.5f, 3.04f, "Nitrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
    hydrogen1 = new Atom(60.0f, 2.20f,"Hydrogen.jpg");
  }


   public void display() {
    hydrogen1.display(x+110.0f, y+25.0f, z-150.0f);
    hydrogen1.display(x+110.0f, y+25.0f, z+150.0f);
    hydrogen1.display(x-150, y+25, z);
    nitrogen.display(x, y, 0);
  }

}


  public void settings() { fullScreen(P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "Main" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
